FROM node:22-slim AS base

RUN npm install -g pnpm typescript turbo

WORKDIR /app

COPY package.json turbo.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY ./apps/worker/package.json ./apps/worker/tsconfig.json ./apps/worker/

COPY ./packages/db/package.json ./packages/db/tsconfig.build.json ./packages/db/
COPY ./packages/embedder/package.json ./packages/embedder/tsconfig.json ./packages/embedder/
COPY ./packages/redis/package.json ./packages/redis/tsconfig.json ./packages/redis/
COPY ./packages/typescript-config ./packages/typescript-config

RUN pnpm install --frozen-lockfile

COPY ./apps/worker/ ./apps/worker/

COPY ./packages/db/ ./packages/db/
COPY ./packages/embedder/ ./packages/embedder/
COPY ./packages/redis/ ./packages/redis/
COPY ./packages/typescript-config/ ./packages/typescript-config/

RUN pnpm build

RUN pnpm --filter=worker --prod deploy /prod/worker

FROM node:22-slim AS runner

RUN apt-get update -y && apt-get install -y \
    openssl \
    ca-certificates \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm

WORKDIR /app

COPY --from=base /prod/worker ./

COPY --from=base /app/apps/worker/dist ./dist

RUN pnpx playwright install-deps chromium \
    && pnpx playwright install chromium

RUN pnpx puppeteer browsers install chrome

RUN mkdir -p models && \
    curl -L -o models/ggml-small.en.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.en.bin

CMD ["node", "dist/index.js"]
