services:
  server:
    build:
      context: .
      dockerfile: docker/dockerfile.server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      SALTROUNDS: ${SALTROUNDS}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

  worker:
    build:
      context: .
      dockerfile: docker/dockerfile.worker
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      CRAWLER_URL: ${CRAWLER_URL}
      ASSEMBLYAI_API_KEY: ${ASSEMBLYAI_API_KEY}
      YT_COOKIES: ${YT_COOKIES}

  crawler:
    build:
      context: .
      dockerfile: docker/dockerfile.crawler
    ports:
      - "${CRAWLER_PORT}:${CRAWLER_PORT}"
    environment:
      CRAWLER_PORT: ${CRAWLER_PORT}
      WEBDRIVER_URL: ${WEBDRIVER_URL}
    depends_on:
      chromedriver:
        condition: service_healthy

  chromedriver:
    image: seleniarm/standalone-chromium:latest
    shm_size: "2g"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 5
