services:
  server:
    build:
      context: .
      dockerfile: docker/dockerfile.server
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      SALTROUNDS: ${SALTROUNDS}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}

  worker:
    build:
      context: .
      dockerfile: docker/dockerfile.worker
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
