[package]
name = "crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
fantoccini = "0.19"
scraper = "0.13"
serde_json = "1.0"

axum = "0.6"
serde = { version = "1.0", features = ["derive"] }
html2text = "0.6"