name: Deploy the backend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Go into VM and docker compose.
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir ~/.ssh
          chmod 700 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.SSH_IP_ADDRESS }} -t 'cd The-Index && git pull && SERVER_PORT="${{ secrets.SERVER_PORT }}" JWT_SECRET="${{ secrets.JWT_SECRET }}" SALTROUNDS="${{ secrets.SALTROUNDS }}" GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" DATABASE_URL="${{ secrets.DATABASE_URL }}" REDIS_URL="${{ secrets.REDIS_URL }}" CRAWLER_URL="${{ secrets.CRAWLER_URL }}" ASSEMBLYAI_API_KEY="${{ secrets.ASSEMBLYAI_API_KEY }}" CRAWLER_PORT="${{ secrets.CRAWLER_PORT }}" WEBDRIVER_URL="${{ secrets.WEBDRIVER_URL }}" YT_COOKIES=${{ secrets.YT_COOKIES}} docker compose up -d --build'
